var data = {
	images: [
		{
			src: [""],
			thumbnail: "",
			title: "Placeholder Entry",
			artist: "Placeholder Entry",
			artist_url: null,
			art_url: null,
			desc: "Do not delete this. You can use this to set the order the tags show up in the dropdown.",
			date_str: "Beginning of Time",
			tags: ["fire_emblem", "porkymon", "rune_factory", "other_series", "larcei", "seliph", "patty", "shannan", "lana", "scathach", "julia", "ayra", "fir", "peri", "hel", "thrasir", "ganglot", "embla", "other_character", "doujin", "sfw", "nsfw"],
			hidden: true
		},
		{
			src: ["https://cdn.imgchest.com/files/myd5cl6a294.png"],
			thumbnail: "https://cdn.imgchest.com/files/3yrgc6nqvd4.png",
			title: "Larcei Thunder Mage",
			artist: "AcrylicStroke",
			artist_url: "https://twitter.com/AcrylicStroke",
			art_url: "https://x.com/AcrylicStroke/status/1616750483435290624?s=20",
			desc: "",
			date_str: "January 2023",
			tags: ["fire_emblem", "larcei", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/wye3c3m9rk4.png", "https://cdn.imgchest.com/files/g4z9cx56ep7.png"],
			thumbnail: "https://cdn.imgchest.com/files/k739c3xal97.png",
			title: "Seliph Masturbation",
			artist: "AthosArt",
			artist_url: "https://twitter.com/AthosArt",
			art_url: "https://x.com/MrTD2020/status/1707968854532714729?s=20",
			desc: "Thinkin about that tomboy",
			date_str: "March 2023",
			tags: ["fire_emblem", "seliph", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/84jdc95lxn4.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/g4z9cdxwjv7.jpg",
			title: "Larcei & Seliph Summer Festival 1",
			artist: "Aquiadok",
			artist_url: "https://twitter.com/aquiadokverse",
			art_url: "https://x.com/MrTalkingDino/status/1578421794565783559?s=20",
			desc: "",
			date_str: "September 2022",
			tags: ["fire_emblem", "larcei", "seliph", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/pyq9cn9wkm4.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/w7pjc6owb67.jpg",
			title: "Tomboy Tavern",
			artist: "Aquiadok",
			artist_url: "https://twitter.com/aquiadokverse",
			art_url: null,
			desc: "A collaboration commission between friends and associates",
			date_str: "April 2022",
			tags: ["fire_emblem", "larcei", "sfw", "other_character"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/l4necvdpgg4.png", "https://cdn.imgchest.com/files/p7bwco5za97.png"],
			thumbnail: "https://cdn.imgchest.com/files/j7kzcn3box7.png",
			title: "Lana & Patty reference sheet",
			artist: "AthosArt",
			artist_url: "https://twitter.com/AthosArt",
			art_url: "https://x.com/MrTD2020/status/1714417100863963451?s=20",
			desc: "My first iteration of designs for Lana and Patty. Once the FE4 Remake comes out, I plan to update their designs slightly.",
			date_str: "October 2023",
			tags: ["fire_emblem", "lana", "patty", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/w7w6cod3wzy.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/my2pc6roxd7.jpg",
			title: "Larcei & Seliph Private Council",
			artist: "Aqrisu",
			artist_url: "https://twitter.com/Aqrisu",
			art_url: "https://x.com/Aqrisu/status/1647847851073101824?s=20",
			desc: "",
			date_str: "April 2023",
			tags: ["fire_emblem", "larcei", "seliph", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/j7kzc3qjp97.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/myd5cblrow4.jpg",
			title: "Larcei found some panties",
			artist: "Aquiadok",
			artist_url: "https://twitter.com/aquiadokverse",
			art_url: null,
			desc: "",
			date_str: "September 2021",
			tags: ["fire_emblem", "larcei", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/l7lxc28qaz7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/b49zczobxvy.jpg",
			title: "Larcei & Seliph Summer Festival 2",
			artist: "Aquiadok",
			artist_url: "https://twitter.com/aquiadokverse",
			art_url: null,
			desc: "",
			date_str: "October 2022",
			tags: ["fire_emblem", "larcei", "seliph", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/l4necvdpzg4.jpg", "https://cdn.imgchest.com/files/my2pcrvgqx7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/w7pjc6owr37.jpg",
			title: "Fir and Larcei Ass Worship",
			artist: "Aquiadok",
			artist_url: "https://twitter.com/aquiadokverse",
			art_url: null,
			desc: "Fir and Larcei appraise each other's ass-ets",
			date_str: "March 2022",
			tags: ["fire_emblem", "larcei", "fir", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/p7bwco5z697.jpg", "https://cdn.imgchest.com/files/w7pjcog3nm7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/k46aczrq9a7.jpg",
			title: "Lana & Scathach Summer 2022",
			artist: "Aquiadok",
			artist_url: "https://twitter.com/aquiadokverse",
			art_url: null,
			desc: "Scathach learned what Lana's name backwards meant.",
			date_str: "May 2022",
			tags: ["fire_emblem", "lana", "scathach", "larcei", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/l7lxc28qez7.png", "https://cdn.imgchest.com/files/myd5cl68ql4.png"],
			thumbnail: "https://cdn.imgchest.com/files/pyq9c6e5gb4.png",
			title: "Larcei & Seliph reference sheet",
			artist: "AthosArt",
			artist_url: "https://twitter.com/AthosArt",
			art_url: "https://x.com/MrTD2020/status/1714405585188536349",
			desc: "My personal reference sheet for Larcei & Seliph. Originally made to simplify their outfits for use in their doujin.",
			date_str: "June 2023",
			tags: ["fire_emblem", "larcei", "seliph", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/84jdc95lk64.png", "https://cdn.imgchest.com/files/myd5cl68qa4.png", "https://cdn.imgchest.com/files/3yrgco2prp4.png", "https://cdn.imgchest.com/files/j7mmc8pdo27.png", "https://cdn.imgchest.com/files/k739cmv2eq7.png"],
			thumbnail: "https://cdn.imgchest.com/files/84jdcbjwnw4.png",
			title: "Larcei & Seliph stealth fellatio",
			artist: "AthosArt",
			artist_url: "https://twitter.com/AthosArt",
			art_url: null,
			desc: "Julia is concerned about her brother's wellbeing. huhuhu",
			date_str: "October 2022",
			tags: ["fire_emblem", "larcei", "seliph", "julia", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/w7w6codabdy.png"],
			thumbnail: "https://cdn.imgchest.com/files/l7lxc6dgn37.png",
			title: "Lana, Larcei, and Patty Flash",
			artist: "AthosArt",
			artist_url: "https://twitter.com/AthosArt",
			art_url: null,
			desc: "Original reference for the body types and pubic hair shapes of my trio of girls.",
			date_str: "July 2022",
			tags: ["fire_emblem", "lana", "larcei", "patty", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/d7ogcnomg8y.png", "https://cdn.imgchest.com/files/j7kzc3qjd97.png"],
			thumbnail: "https://cdn.imgchest.com/files/w7w6crk2apy.png",
			title: "Larcei & Seliph Maid Cafe",
			artist: "AthosArt",
			artist_url: "https://twitter.com/AthosArt",
			art_url: "https://x.com/AthosArt/status/1678839773840932865",
			desc: "Seliph and Larcei are slacking off at their new job.",
			date_str: "July 2023",
			tags: ["fire_emblem", "larcei", "seliph", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/pyvdc63wkky.png"],
			thumbnail: "https://cdn.imgchest.com/files/k739c3qx2o7.png",
			title: "Larcei & Seliph's legs",
			artist: "AthosArt",
			artist_url: "https://twitter.com/AthosArt",
			art_url: "https://x.com/AthosArt/status/1692227493581742238",
			desc: "How nice of Seliph to help Larcei reach something off the top shelf.",
			date_str: "August 2023",
			tags: ["fire_emblem", "larcei", "seliph", "julia", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/b49zcodqm2y.png"],
			thumbnail: "https://cdn.imgchest.com/files/j7mmc5b9dq7.png",
			title: "Brigid caught Dew peeping",
			artist: "AthosArt",
			artist_url: "https://twitter.com/AthosArt",
			art_url: null,
			desc: "Proof of concept for a doujin I have planned of Brigid x Dew.",
			date_str: "January 2023",
			tags: ["fire_emblem", "other_character", "nsfw"],
			hidden: false
		},
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			art_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		}
	]
};
